package br.gov.es.siscap.dto;

import br.gov.es.siscap.models.Projeto;
import br.gov.es.siscap.models.StatusProjeto;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public record ProjetoDto(
		Long id,
		String sigla,
		String titulo,
		String status,
		ValorDto valor,
		String objetivo,
		String objetivoEspecifico,
		Long idStatus,
		Long idOrganizacao,
		String situacaoProblema,
		String solucoesPropostas,
		String impactos,
		String arranjosInstitucionais,
		List<RateioDto> rateio,
		Long idResponsavelProponente,
		List<EquipeDto> equipeElaboracao,
		Boolean rascunho,
		String subResponsavelProponente,
		List<ProjetoIndicadorDto> indicadoresProjeto,
		List<ProjetoAcaoDto> acoesProjeto,
		String pecasPlanejamento,
		String protocoloEdocs,
		String subProponente,
		String lotacaoProponenteResponsavel,
		String nomeProponenteResponsavel,
		Boolean podeEditar,
		Boolean podeSolicitarComplementacao,
		Boolean podeResponderComplementacao,
		String idProcessoEdocs,
		String idDocumentoDicEdocs,
		List<ProjetoCamposComplementacaoDto> camposComplementar,
		ProjetoParecerDto parecerProjetoUsuario,
		Long lotacaoUsuario,
		List<ProjetoParecerDto> pareceresProjeto,
		String nomeProponente,
		List<StatusProjetoDto> historico,
		List<ProjetoIndicadorAvulsoDto> indicadoresAvulsosProjeto,
		List<ProjetoOdsDto> odsProjeto
	) {

	public ProjetoDto(Projeto projeto,
			ValorDto valor,
			List<RateioDto> rateio,
			Long idResponsavelProponente,
			List<EquipeDto> equipeElaboracao,
			String subResponsavelProponente,
			List<ProjetoIndicadorDto> indicadoresProjeto,
			List<ProjetoAcaoDto> acoesProjeto,
			String subProponente,
			String lotacaoProponenteResponsavel, 
			String nomeProponenteResponsavel, 
			Boolean podeEditar,
			Boolean podeSolicitarComplementacao,
			Boolean podeResponderComplementacao,
			String idProcessoEdocs,
			String idDocumentoDicEdocs,
			List<ProjetoCamposComplementacaoDto> camposComplementar,
			ProjetoParecerDto parecerProjeto,
			Long lotacaoUsuario,
			List<ProjetoParecerDto> pareceresProjeto,
			String nomeProponente,
			List<StatusProjetoDto> historico,
			List<ProjetoIndicadorAvulsoDto> projetoIndicadorAvulsos,
			List<ProjetoOdsDto> odsProjeto) {

		this(projeto.getId(),
				projeto.getSigla(),
				projeto.getTitulo(),
				Optional.ofNullable(projeto.getStatusAtual()).map(StatusProjeto::getStatus).orElse(null),
				valor,
				projeto.getObjetivo(),
				projeto.getObjetivoEspecifico(),
				projeto.getTipoStatus().getId(),
				projeto.getOrganizacao().getId(),
				projeto.getSituacaoProblema(),
				projeto.getSolucoesPropostas(),
				projeto.getImpactos(),
				projeto.getArranjosInstitucionais(),
				rateio,
				idResponsavelProponente,
				equipeElaboracao,
				projeto.isRascunho(),
				subResponsavelProponente,
				indicadoresProjeto,
				acoesProjeto,
				projeto.getPecasPlanejamento(),
				projeto.getProtocoloEdocs(),
				subProponente,
				lotacaoProponenteResponsavel,
				nomeProponenteResponsavel,
				podeEditar,
				podeSolicitarComplementacao,
				podeResponderComplementacao,
				idProcessoEdocs,
				idDocumentoDicEdocs,
				camposComplementar,
				parecerProjeto,
				lotacaoUsuario,
				pareceresProjeto,
				nomeProponente,
				historico,
				projetoIndicadorAvulsos,
				odsProjeto);

	}

	public ProjetoDto(Projeto projeto) {
		this(projeto.getId(),
				projeto.getSigla(),
				projeto.getTitulo(),
				Optional.ofNullable(projeto.getStatusAtual()).map(StatusProjeto::getStatus).orElse(null),
				null,
				projeto.getObjetivo(),
				projeto.getObjetivoEspecifico(),
				projeto.getTipoStatus().getId(),
				projeto.getOrganizacao().getId(),
				projeto.getSituacaoProblema(),
				projeto.getSolucoesPropostas(),
				projeto.getImpactos(),
				projeto.getArranjosInstitucionais(),
				null,
				null,
				null,
				projeto.isRascunho(),
				null,
				null,
				null,
				projeto.getPecasPlanejamento(),
				projeto.getProtocoloEdocs(),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null, 
				null,
				projeto.getProjetoParecerSet().stream().map(ProjetoParecerDto::new).toList(), 
				"",
				Optional.ofNullable(projeto.getHistoricoStatus()).map(hl -> hl.stream().map(StatusProjetoDto::new).toList()).orElse(new ArrayList<>()),
				projeto.getProjetoIndicadorAvulsoSet().stream().map(ProjetoIndicadorAvulsoDto::new).toList(),
				projeto.getOds().stream().map(ProjetoOdsDto::new).toList());

	}

}