package br.gov.es.siscap.dto;

import br.gov.es.siscap.models.Projeto;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;

public record ProjetoDto(
		Long id,
		String sigla,
		String titulo,
		String status,
		ValorDto valor,
		String objetivo,
		String objetivoEspecifico,
		Long idStatus,
		Long idOrganizacao,
		String situacaoProblema,
		String solucoesPropostas,
		String impactos,
		String arranjosInstitucionais,
		List<RateioDto> rateio,
		Long idResponsavelProponente,
		List<EquipeDto> equipeElaboracao,
		Boolean rascunho,
		String subResponsavelProponente,
		List<ProjetoIndicadorDto> indicadoresProjeto,
		List<ProjetoAcaoDto> acoesProjeto,
		String pecasPlanejamento,
		String protocoloEdocs,
		String subProponente,
		String lotacaoProponenteResponsavel,
		String nomeProponenteResponsavel,
		Boolean podeEditar,
		Boolean podeSolicitarComplementacao,
		Boolean podeResponderComplementacao,
		String idProcessoEdocs,
		String idDocumentoDicEdocs,
		List<ProjetoCamposComplementacaoDto> camposComplementar,
		ProjetoParecerDto parecerProjetoUsuario,
		Long lotacaoUsuario,
		List<ProjetoParecerDto> pareceresProjeto,
		String nomeProponente,
                List<StatusProjetoDto> historico
        ) {

	public ProjetoDto(Projeto projeto, ValorDto valor, List<RateioDto> rateio, Long idResponsavelProponente,
			List<EquipeDto> equipeElaboracao,
			String subResponsavelProponente, List<ProjetoIndicadorDto> indicadoresProjeto,
			List<ProjetoAcaoDto> acoesProjeto, String subProponente,
			String lotacaoProponenteResponsavel, String nomeProponenteResponsavel, Boolean podeEditar,
			Boolean podeSolicitarComplementacao,
			Boolean podeResponderComplementacao, String idProcessoEdocs, String idDocumentoDicEdocs,
			List<ProjetoCamposComplementacaoDto> camposComplementar,
			ProjetoParecerDto parecerProjeto, Long lotacaoUsuario, List<ProjetoParecerDto> pareceresProjeto, String nomeProponente, List<StatusProjetoDto> historico) {
		this(projeto.getId(),
				projeto.getSigla(),
				projeto.getTitulo(),
				projeto.getStatusAtual().getStatus(),
				valor,
				projeto.getObjetivo(),
				projeto.getObjetivoEspecifico(),
				projeto.getTipoStatus().getId(),
				projeto.getOrganizacao().getId(),
				projeto.getSituacaoProblema(),
				projeto.getSolucoesPropostas(),
				projeto.getImpactos(),
				projeto.getArranjosInstitucionais(),
				rateio,
				idResponsavelProponente,
				equipeElaboracao,
				projeto.isRascunho(),
				subResponsavelProponente,
				indicadoresProjeto,
				acoesProjeto,
				projeto.getPecasPlanejamento(),
				projeto.getProtocoloEdocs(),
				subProponente,
				lotacaoProponenteResponsavel,
				nomeProponenteResponsavel,
				podeEditar,
				podeSolicitarComplementacao,
				podeResponderComplementacao,
				idProcessoEdocs,
				idDocumentoDicEdocs,
				camposComplementar,
				parecerProjeto, lotacaoUsuario, pareceresProjeto, nomeProponente,
                                historico);

	}

	public ProjetoDto(Projeto projeto) {
		this(projeto.getId(),
				projeto.getSigla(),
				projeto.getTitulo(),
				projeto.getStatusAtual().getStatus(),
				null,
				projeto.getObjetivo(),
				projeto.getObjetivoEspecifico(),
				projeto.getTipoStatus().getId(),
				projeto.getOrganizacao().getId(),
				projeto.getSituacaoProblema(),
				projeto.getSolucoesPropostas(),
				projeto.getImpactos(),
				projeto.getArranjosInstitucionais(),
				null,
				null,
				null,
				projeto.isRascunho(),
				null,
				null,
				null,
				projeto.getPecasPlanejamento(),
				projeto.getProtocoloEdocs(),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null, null, 
				projeto.getProjetoParecerSet().stream().map(ProjetoParecerDto::new).toList(), "" ,
                                Optional.ofNullable(projeto.getHistoricoStatus()).map(hl -> hl.stream().map(StatusProjetoDto::new).toList()).orElse(new ArrayList<>()));

	}

}