spring:
  datasource:
    url: jdbc:postgresql://10.243.135.48:5432/siscap
    username: postgres
    password: kvRfzFXWhUCM5kYTbr5OV7Kk0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 37a8c577b86c51
    password: 300531ac19c0d5
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  flyway:
    url: jdbc:postgresql://10.243.135.48:5432/siscap
    user: postgres
    password: kvRfzFXWhUCM5kYTbr5OV7Kk0
    enabled: true

  security:
    oauth2:
      client:
        provider:
          acessocidadao:
            issuer-uri: https://acessocidadao.es.gov.br/is
        registration:
          acessocidadao:
            client-name: siscap
            client-id: 5527294c-228f-476a-b672-4ba76c0ca118
            client-secret: 19j8hUHrAPPn@@JyeTtHZD1*ZnFd6j
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/siscap/acesso-cidadao-response.html
            scope:
               - api-sigades
               - api-sigades-processo
               - api-sigades-documento
               - api-sigades-consultar
               - api-sigades-encaminhamento
               - openid
               - profile
               - nome
               - agentepublico
               - email
               - roles
               - permissoes
               - emailCorporativo
               - ApiAcessoCidadao
               - ApiOrganograma
               - api-acessocidadao-cpf
               - api-acessocidadao-base
               - api-organograma
               - api-acessocidadao-servidores
      resourceserver:
        jwt:
          issuer-uri: https://acessocidadao.es.gov.br/is

api:
  acessocidadao:
    uri:
      token: https://acessocidadao.es.gov.br/is/connect/token
      webapi: https://sistemas.es.gov.br/prodest/acessocidadao.webapi
      userinfo: https://acessocidadao.es.gov.br/is/connect/userinfo
    client-id: af311882-53a8-495e-874e-8c98d825c007
    client-secret: HlvbBUqcKIIpy67Fo8$rgIt*yG$GHK
    grant_type: client_credentials
    scope: ApiAcessoCidadao ApiOrganograma api-acessocidadao-cpf api-acessocidadao-base api-organograma api-acessocidadao-servidores api-sigades-documento
  organograma:
    uri:
      webapi: https://api.organograma.es.gov.br
  edocs:
    uri:
      webapi: https://api.treinamento.e-docs.es.gov.br
    classedocumento-id: 66c3fb09-bcdc-468e-a365-5cb5f8eef6b6
    guiddestinoSUBCAP: 515685f7-2aeb-4cc4-a311-8b793297f8fb

frontend:
  host: http://localhost:4200

raiz:
  imagens: C:/siscap/api/arquivos/imagens
  relatorios: jasper
  documentos: C:/siscap/api/arquivos/documentos

authorities:
  file: C:/siscap/api/authorities-mapping.json

token:
  secret: eXEuFkMDTTEX24UtGF2UQsCdylQVrjHxqe16DYdiSgo8oclXXqyAroPJjiE0OE95

email:
  remetente:
    endereco: captacao@sep.es.gov.br
    apelido: Governo do Estado do Espirito Santo
    endereco-nao-responda: naoresponda@sep.es.gov.br
    
guidGOVES: "fe88eb2a-a1f3-4cb1-a684-87317baf5a57"

server:
  ssl:
    enabled: false
  port: 8080
  servlet:
    context-path: /siscap

logging:
  level:
    root: INFO
    feign: DEBUG
    feign.Logger: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG
        
  file:
    name: api-error.log 

listarpapeisprioritarios: false