spring:
  application:
    name: SISCAP
    version: 1.0.0
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /siscap

log4j:
  skipJansi: false

raiz:
  imagens: C:/projetos/siscap/img
  relatorios: C:/projetos/siscap/relatorios
  documentos: C:/projetos/siscap/documentos