spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siscap_2
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 37a8c577b86c51
    password: 300531ac19c0d5
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  flyway:
    url: jdbc:postgresql://localhost:5432/siscap
    user: postgres
    password: postgres
    enabled: true

  security:
    oauth2:
      client:
        provider:
          acessocidadao:
            issuer-uri: https://acessocidadao.es.gov.br/is
        registration:
          acessocidadao:
            client-name: siscap
            client-id: 5527294c-228f-476a-b672-4ba76c0ca118
            client-secret: 19j8hUHrAPPn@@JyeTtHZD1*ZnFd6j
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/siscap/acesso-cidadao-response.html
            scope:
               - openid
               - profile
               - agentepublico
               - email				
               - roles				
               - permissoes	 		
               - emailCorporativo	
               - nome	 			
               - ApiAcessoCidadao	 			
               - ApiOrganograma	 				
               - api-acessocidadao-cpf	 		
               - api-acessocidadao-base	 		
               - api-acessocidadao-servidores	
               - api-organograma	 					 			
               - api-sigades	 					
               - api-sigades-documento	 		
               - api-sigades-processo	 		
               - api-sigades-consultar	 		
               - api-sigades-encaminhamento
      resourceserver:
        jwt:
          issuer-uri: https://acessocidadao.es.gov.br/is

api:
  acessocidadao:
    uri:
      token: https://acessocidadao.es.gov.br/is/connect/token
      webapi: https://sistemas.es.gov.br/prodest/acessocidadao.webapi
      userinfo: https://acessocidadao.es.gov.br/is/connect/userinfo
    client-id: af311882-53a8-495e-874e-8c98d825c007
    client-secret: HlvbBUqcKIIpy67Fo8$rgIt*yG$GHK
    grant_type: client_credentials
    scope: ApiAcessoCidadao ApiOrganograma api-acessocidadao-cpf api-acessocidadao-base api-organograma api-acessocidadao-servidores api-sigades-documento
  organograma:
    uri:
      webapi: https://api.organograma.es.gov.br
    sync:
      organizacoes-cron: "0 0 7 * * *" # "0 0 13 * * *" # todos os dias as 13 horas #"0 */10 * * * *" # a cada 10 minutos # "0 0 7 * * *" # todos os dias a 7 da manha
  edocs:
    uri:
      webapi: https://api.treinamento.e-docs.es.gov.br
    classedocumento-id: 66c3fb09-bcdc-468e-a365-5cb5f8eef6b6
    guiddestinoSUBCAP: 515685f7-2aeb-4cc4-a311-8b793297f8fb # (SUBCAP) # d2ab305b-3f41-4802-b509-09f447ab3016 # (CGTI) 
  parecer:
    guidSUBEPP: 90948693-1692-49df-a5d1-7d1ce84f600b # SUBEPP
    guidSUBEO: 5821ad81-5f09-4122-a738-844929c7c620 # SUBEO
    lotacao:
      simulada: 515685f7-2aeb-4cc4-a311-8b793297f8fb # (SUBCAP)
  programa:
    assinantes:
      gestorSUBCAP: 5fca5728-7e33-4969-82b0-18349faec213 # Renata # 0e3852c0-9b57-416a-ac63-ac267cd65055 # gestor SUBCAP ( ANDRESSA PAVAO )
      gestorSEP: b2320148-bc66-4998-ae59-6e9c876808d4 # Ricardo # e7942272-bb41-4d32-9c51-de3145ebcf21 # Vagner # c1ab19d7-bc5f-48f7-aa94-52e1f2b37831 # gestor SEP ( ALVARO DUBOC )
      gestorGOVES: d2c2c928-ddcc-4f0a-b58d-0ffcab7f31e3 # Eduardo # 4935701b-37cf-4638-ab23-b3f6b464547d # Thassia # 7a6cd93e-e134-4238-b39e-36acd3e199f8 # gestor GOVES ( JOSE RENATO CASAGRANDE )

frontend:
  host: http://localhost:4200
  edocs:
    host: https://treinamento.e-docs.es.gov.br

raiz:
  imagens: C:/siscap/api/arquivos/imagens
  relatorios: jasper
  documentos: C:/siscap/api/arquivos/documentos

authorities:
  file: C:/siscap/api/authorities-mapping.json

token:
  secret: eXEuFkMDTTEX24UtGF2UQsCdylQVrjHxqe16DYdiSgo8oclXXqyAroPJjiE0OE95

email:
  remetente:
    endereco: captacao@sep.es.gov.br
    apelido: Governo do Estado do Espirito Santo
    endereco-nao-responda: naoresponda@sep.es.gov.br
  destinatario-parecer:
    orcamentario: gabsubeo@sep.es.gov.br # "Gabinete Subeo" <gabsubeo@sep.es.gov.br>
    estrategico: gabinete.subepp@sep.es.gov.br # "gabinete.subepp" <gabinete.subepp@sep.es.gov.br>; 
  destinatario-subcap: subcap@sep.es.gov.br
  gerencia-subcap: gabinetesubcap@sep.es.gov.br

guidGOVES: "fe88eb2a-a1f3-4cb1-a684-87317baf5a57"

server:
  ssl:
    enabled: false
  port: 8080
  servlet:
    context-path: /siscap

logging:
  level:
    root: INFO
    org.springframework.security.oauth2: DEBUG

  file:
    name: api-error.log 

listarpapeisprioritarios: false