package br.gov.es.siscap.enums;

public enum Permissoes {

    ADMIN_AUTH,
    PESSOA_CADASTRAR,
    PESSOA_ATUALIZAR,
    PESSOA_APAGAR,
    PROJETO_CADASTRAR,
    PROJETO_ATUALIZAR,
    PROJETO_APAGAR,
    ORGANIZACAO_CADASTRAR,
    ORGANIZACAO_ATUALIZAR,
    ORGANIZACAO_APAGAR
}
