package br.gov.es.siscap.enums;

public enum Permissoes {

	ADMIN_AUTH,
	PESSOA_CADASTRAR,
	PESSOA_ATUALIZAR,
	PESSOA_APAGAR,
	PROJETO_CADASTRAR,
	PROJETO_ATUALIZAR,
	PROJETO_APAGAR,
	PROGRAMA_CADASTRAR,
	PROGRAMA_ATUALIZAR,
	PROGRAMA_APAGAR,
	ORGANIZACAO_CADASTRAR,
	ORGANIZACAO_ATUALIZAR,
	ORGANIZACAO_APAGAR,
	CARTA_CONSULTA_CADASTRAR,
	CARTA_CONSULTA_ATUALIZAR,
	CARTA_CONSULTA_APAGAR,
	PROSPECCAO_CADASTRAR,
	PROSPECCAO_ATUALIZAR,
	PROSPECCAO_APAGAR;
}
