
CREATE TABLE indicador_avulso (
    id                  SERIAL CONSTRAINT pk_indicador_avulso PRIMARY KEY,
    nome_indicador      VARCHAR(2000) NOT NULL,
    unidade_medida      VARCHAR(2000) NOT NULL,
    fonte_indicador     VARCHAR(2000) NOT NULL,
    medido_por          VARCHAR(2000) NOT NULL,
    base_de_referencia  VARCHAR(2000) NOT NULL,
    apagado             BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em           TIMESTAMP NOT NULL,
    atualizado_em       TIMESTAMP NOT NULL
);

CREATE TABLE indicador_avulso_meta (
    id                      SERIAL CONSTRAINT pk_indicador_avulso_meta PRIMARY KEY,
    id_indicador_avulso     INTEGER NOT NULL,
    ano                     INTEGER NOT NULL,
    valor                   VARCHAR(255) NOT NULL,
    apagado                 BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em               TIMESTAMP NOT NULL,
    atualizado_em           TIMESTAMP NOT NULL
);

ALTER TABLE indicador_avulso_meta
    ADD CONSTRAINT fk_indicador_avulso_meta_indicador
    FOREIGN KEY (id_indicador_avulso)
    REFERENCES indicador_avulso(id);

---------------------------------------------------------

CREATE TABLE projeto_indicador_avulso (
    id                      SERIAL CONSTRAINT pk_projeto_indicador_avulso PRIMARY KEY,
    id_projeto              INTEGER NOT NULL,
    id_indicador_avulso     INTEGER NOT NULL,
    apagado                 BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em               TIMESTAMP NOT NULL,
    atualizado_em           TIMESTAMP NOT NULL
);

ALTER TABLE projeto_indicador_avulso
    ADD CONSTRAINT fk_projeto_indicador_avulso_projeto
    FOREIGN KEY (id_projeto)
    REFERENCES projeto(id);

ALTER TABLE projeto_indicador_avulso
    ADD CONSTRAINT fk_projeto_indicador_avulso_indicador
    FOREIGN KEY (id_indicador_avulso)
    REFERENCES indicador_avulso(id);

---------------------------------------------------------

CREATE TABLE projeto_indicador_avulso_meta (
    id                                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projeto_indicador_avulso         INTEGER NOT NULL,
    ano                                 INTEGER NOT NULL,
    valor                               VARCHAR(255) NOT NULL,
    apagado                             BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em                           TIMESTAMP,
    atualizado_em                       TIMESTAMP
);

ALTER TABLE projeto_indicador_avulso_meta
    ADD CONSTRAINT fk_projeto_indicador_avulso_meta
    FOREIGN KEY (id_projeto_indicador_avulso)
    REFERENCES projeto_indicador_avulso(id);

-- criar indices para as FK´s
CREATE INDEX idx_indicador_avulso_meta_indicador
ON indicador_avulso_meta(id_indicador_avulso);

CREATE INDEX idx_projeto_indicador_avulso_projeto
ON projeto_indicador_avulso(id_projeto);

CREATE INDEX idx_projeto_indicador_avulso_indicador
ON projeto_indicador_avulso(id_indicador_avulso);

CREATE INDEX idx_projeto_indicador_avulso_meta_rel
ON projeto_indicador_avulso_meta(id_projeto_indicador_avulso);

-- evitar duplicidade
ALTER TABLE projeto_indicador_avulso
    ADD CONSTRAINT uk_projeto_indicador
    UNIQUE (id_projeto, id_indicador_avulso);