alter table pais alter column continente drop not null;
alter table pais alter column subcontinente drop not null;
alter table pais alter column ddi drop not null;

INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('2', 'Afeganistão', 'AFG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('3', 'África do Sul', 'ZAF', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('4', 'Albânia', 'ALB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('5', 'Alemanha', 'DEU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('6', 'Andorra', 'AND', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('7', 'Angola', 'AGO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('8', 'Anguilla', 'AIA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('9', 'Antígua e Barbuda', 'ATG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('10', 'Arábia Saudita', 'SAU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('11', 'Argélia', 'DZA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('12', 'Argentina', 'ARG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('13', 'Armênia', 'ARM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('14', 'Aruba', 'ABW', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('15', 'Austrália', 'AUS', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('16', 'Áustria', 'AUT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('17', 'Azerbaijão', 'AZE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('18', 'Bahamas', 'BHS', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('19', 'Bangladesh', 'BGD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('20', 'Barbados', 'BRB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('21', 'Barein', 'BHR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('22', 'Bélgica', 'BEL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('23', 'Belize', 'BLZ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('24', 'Benin', 'BEN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('25', 'Bermuda', 'BMU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('26', 'Bielorússia', 'BLR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('27', 'Bolívia', 'BOL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('28', 'Bonaire, Santo Eustáquio e Saba', 'BES', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('29', 'Bósnia-Herzegovina', 'BIH', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('30', 'Botsuana', 'BWA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('32', 'Brunei', 'BRN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('33', 'Bulgária', 'BGR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('34', 'Burkina Faso', 'BFA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('35', 'Burundi', 'BDI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('36', 'Butão', 'BTN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('37', 'Cabo Verde', 'CPV', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('38', 'Camarões', 'CMR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('39', 'Camboja', 'KHM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('40', 'Canadá', 'CAN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('41', 'Casaquistão', 'KAZ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('42', 'Catar', 'QAT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('43', 'Chade', 'TCD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('44', 'Chile', 'CHL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('45', 'China', 'CHN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('46', 'China, Hong Kong', 'HKG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('47', 'China, Macao', 'MAC', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('48', 'Chipre', 'CYP', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('49', 'Cingapura', 'SGP', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('50', 'Colômbia', 'COL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('51', 'Comores', 'COM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('52', 'Congo', 'COG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('53', 'Coréia do Norte', 'PRK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('54', 'Coréia do Sul', 'KOR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('55', 'Costa do Marfim', 'CIV', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('56', 'Costa Rica', 'CRI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('57', 'Croácia', 'HRV', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('58', 'Cuba', 'CUB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('59', 'Curaçao', 'CUW', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('60', 'Dinamarca', 'DNK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('61', 'Djibouti', 'DJI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('62', 'Dominica', 'DMA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('63', 'Egito', 'EGY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('64', 'El Salvador', 'SLV', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('65', 'Emirados Árabes Unidos', 'ARE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('66', 'Equador', 'ECU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('67', 'Eritréia', 'ERI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('68', 'Eslováquia', 'SVK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('69', 'Eslovênia', 'SVN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('70', 'Espanha', 'ESP', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('71', 'Estados Unidos da América', 'USA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('72', 'Estônia', 'EST', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('73', 'Etiópia', 'ETH', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('74', 'Fiji', 'FJI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('75', 'Filipinas', 'PHL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('76', 'Finlândia', 'FIN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('77', 'França', 'FRA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('78', 'Gabão', 'GAB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('79', 'Gâmbia', 'GMB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('80', 'Gana', 'GHA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('81', 'Geórgia', 'GEO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('82', 'Gibraltar', 'GIB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('83', 'Granada', 'GRD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('84', 'Grécia', 'GRC', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('85', 'Groenlândia', 'GRL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('86', 'Guam', 'GUM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('87', 'Guatemala', 'GTM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('88', 'Guernsey', 'GGY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('89', 'Guiana', 'GUY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('90', 'Guiana Francesa', 'GUF', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('91', 'Guiné', 'GIN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('92', 'Guiné Equatorial', 'GNQ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('93', 'Guiné-Bissau', 'GNB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('94', 'Haiti', 'HTI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('95', 'Holanda', 'NLD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('96', 'Honduras', 'HND', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('97', 'Hungria', 'HUN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('98', 'Iêmen', 'YEM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('99', 'Ilha de Man', 'IMN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('100', 'Ilha Guadalupe', 'GLP', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('101', 'Ilha Norfolk', 'NFK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('102', 'Ilha Reunião', 'REU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('103', 'Ilhas Alanda', 'ALA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('104', 'Ilhas Cayman', 'CYM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('105', 'Ilhas Cook', 'COK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('106', 'Ilhas do Canal', '', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('107', 'Ilhas Faeroe', 'FRO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('108', 'Ilhas Falkland', 'FLK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('109', 'Ilhas Marianas', 'MNP', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('110', 'Ilhas Marshall', 'MHL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('111', 'Ilhas Salomão', 'SLB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('112', 'Ilhas Turks e Caicos', 'TCA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('113', 'Ilhas Virgens', 'VIR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('114', 'Ilhas Virgens Britânicas', 'VGB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('115', 'Ilhas Wallis e Futuna', 'WLF', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('116', 'Índia', 'IND', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('117', 'Indonésia', 'IDN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('118', 'Irã', 'IRN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('119', 'Iraque', 'IRQ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('120', 'Irlanda', 'IRL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('121', 'Islândia', 'ISL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('122', 'Israel', 'ISR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('123', 'Itália', 'ITA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('124', 'Jamaica', 'JAM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('125', 'Japão', 'JPN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('126', 'Jersey', 'JEY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('127', 'Jordânia', 'JOR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('128', 'Kiribati', 'KIR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('129', 'Kuwait', 'KWT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('130', 'Laos', 'LAO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('131', 'Lesoto', 'LSO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('132', 'Letônia', 'LVA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('133', 'Líbano', 'LBN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('134', 'Libéria', 'LBR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('135', 'Líbia', 'LBY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('136', 'Liechtenstein', 'LIE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('137', 'Lituânia', 'LTU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('138', 'Luxemburgo', 'LUX', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('139', 'Macedônia', 'MKD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('140', 'Madagáscar', 'MDG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('141', 'Malásia', 'MYS', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('142', 'Malauí', 'MWI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('143', 'Maldivas', 'MDV', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('144', 'Mali', 'MLI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('145', 'Malta', 'MLT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('146', 'Marrocos', 'MAR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('147', 'Martinica', 'MTQ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('148', 'Maurício', 'MUS', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('149', 'Mauritânia', 'MRT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('150', 'Mayotte', 'MYT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('151', 'México', 'MEX', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('152', 'Mianma', 'MMR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('153', 'Micronésia', 'FSM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('154', 'Moçambique', 'MOZ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('155', 'Moldávia', 'MDA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('156', 'Mônaco', 'MCO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('157', 'Mongólia', 'MNG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('158', 'Montenegro', 'MNE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('159', 'Montserrat', 'MSR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('160', 'Namíbia', 'NAM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('161', 'Nauru', 'NRU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('162', 'Nepal', 'NPL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('163', 'Nicarágua', 'NIC', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('164', 'Níger', 'NER', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('165', 'Nigéria', 'NGA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('166', 'Niue', 'NIU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('167', 'Noruega', 'NOR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('168', 'Nova Caledônia', 'NCL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('169', 'Nova Zelândia', 'NZL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('170', 'Omã', 'OMN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('171', 'Palau', 'PLW', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('172', 'Palestina', 'PSE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('173', 'Panamá', 'PAN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('174', 'Papua Nova Guiné', 'PNG', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('175', 'Paquistão', 'PAK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('176', 'Paraguai', 'PRY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('177', 'Peru', 'PER', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('178', 'Pitcairn', 'PCN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('179', 'Polinésia Francesa', 'PYF', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('180', 'Polônia', 'POL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('181', 'Porto Rico', 'PRI', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('182', 'Portugal', 'PRT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('183', 'Quênia', 'KEN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('184', 'Quirguistão', 'KGZ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('185', 'Reino Unido', 'GBR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('186', 'República Centro Africana', 'CAF', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('187', 'República Democrática do Congo', 'COD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('188', 'República Dominicana', 'DOM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('189', 'República Tcheca', 'CZE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('190', 'Romênia', 'ROU', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('191', 'Ruanda', 'RWA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('192', 'Rússia (Federação Russa)', 'RUS', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('193', 'Saara Ocidental', 'ESH', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('194', 'Saint Martin (parte francesa)', 'MAF', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('195', 'Saint Martin (parte holandesa)', 'SXM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('196', 'Saint Pierre e Miquelon', 'SPM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('197', 'Samoa', 'WSM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('198', 'Samoa Americana', 'ASM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('199', 'San Marino', 'SMR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('200', 'Santa Helena', 'SHN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('201', 'Santa Lúcia', 'LCA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('202', 'São Bartolomeu', 'BLM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('203', 'São Cristóvão e Nevis', 'KNA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('204', 'São Tome e Príncipe', 'STP', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('205', 'São Vicente e Granadinas', 'VCT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('206', 'Sark', ' ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('207', 'Seichelles', 'SYC', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('208', 'Senegal', 'SEN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('209', 'Serra Leoa', 'SLE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('210', 'Sérvia', 'SRB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('211', 'Síria', 'SYR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('212', 'Somália', 'SOM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('213', 'Sri Lanka', 'LKA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('214', 'Suazilândia', 'SWZ', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('215', 'Sudão do Sul', 'SSD', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('216', 'Sudão', 'SDN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('217', 'Suécia', 'SWE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('218', 'Suíça', 'CHE', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('219', 'Suriname', 'SUR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('220', 'Svalbard e Jan Mayen Islands', 'SJM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('221', 'Tadjiquistão', 'TJK', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('222', 'Tailândia', 'THA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('223', 'Tanzânia', 'TZA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('224', 'Timor Leste', 'TLS', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('225', 'Togo', 'TGO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('226', 'Tokelau', 'TKL', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('227', 'Tonga', 'TON', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('228', 'Trinidad e Tobago', 'TTO', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('229', 'Tunísia', 'TUN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('230', 'Turcomenistão', 'TKM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('231', 'Turquia', 'TUR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('232', 'Tuvalu', 'TUV', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('233', 'Ucrânia', 'UKR', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('234', 'Uganda', 'UGA', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('235', 'Uruguai', 'URY', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('236', 'Uzbequistão', 'UZB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('237', 'Vanuatu', 'VUT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('238', 'Vaticano', 'VAT', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('239', 'Venezuela', 'VEN', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('240', 'Vietnã', 'VNM', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('241', 'Zâmbia', 'ZMB', 'false');
INSERT INTO pais (id, nome, iso_alpha_3, apagado) VALUES ('242', 'Zimbábue', 'ZWE', 'false');
